### ISSUE TITLE
Webapi and inverter not running any more since 2024.7

### ISSUE THREAD

**Issue by pietnie** [marq24/ha-senec-v3#99]
### With which version of the integration you have an issue?

SENEC.Home V3 hybrid/SENEC.Home V3 hybrid duo/SENEC.Home V2.1 (or older) 

### Multiple Systems Environment?

- [ ] I have multiple SENEC Systems (master/slave configuration)

### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I understand the SHIT-__IN__ - SHIT-__OUT__ principle (in case of implausible data) | It will happen, that the data that is displayed by this integration does not make much sense (to you) - Of course this could be always the case, that something in this integration has been messed up - but so far - in all reported issues the root cause of implausible data was/is, that the SENEC.Home device itself already provided this data
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

Since update to 2024.7 both webapi and  inverter cannot start anymore, furthermore different warnings appear like the following

ENERGY_KILO_WATT_HOUR was used from senec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfEnergy.KILO_WATT_HOUR instead, please report it to the author of the 'senec' custom integration
POWER_WATT was used from senec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.WATT instead, please report it to the author of the 'senec' custom integration
POWER_KILO_WATT was used from senec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfPower.KILO_WATT instead, please report it to the author of the 'senec' custom integration
TEMP_CELSIUS was used from senec, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'senec' custom integration

### Add your DEBUG log output

```shell
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senec/__init__.py", line 89, in async_setup_entry
    coordinator = SenecDataUpdateCoordinator(hass, session, config_entry, langDict=_LANG)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senec/__init__.py", line 186, in __init__
    self.senec = MySenecWebPortal(user=user, pwd=pwd, websession=session,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/senec/pysenec_ha/__init__.py", line 1851, in __init__
    loop = aiohttp.helpers.get_running_loop(websession.loop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'aiohttp.helpers' has no attribute 'get_running_loop'
```

**Comment by pietnie** [comment]
Please delete, the integration was not updated, a new install was successfull

**Comment by pietnie** [comment]
Can someone please delete this bug ? Thanks
